### ISSUE TITLE
Why I get this warning when run build with webpack?

### ISSUE THREAD

**Issue by alesoto13** [john555/express-app-typescript#1]
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

**Comment by john555** [comment]
Hi @asotoglez, In this [tutorial](https://medium.com/the-andela-way/how-to-set-up-an-express-api-using-webpack-and-typescript-69d18c8c4f52), in the final thoughts section, I mentioned this.

> Running yarn start:dev yields a deprecation warning. This is because webpack-shell-plugin is using webpack’s old plugin API. You can follow up about this on this [issue](https://github.com/1337programming/webpack-shell-plugin/issues/61).

**Comment by alesoto13** [comment]
> Hi @asotoglez, In this [tutorial](https://medium.com/the-andela-way/how-to-set-up-an-express-api-using-webpack-and-typescript-69d18c8c4f52), in the final thoughts section, I mentioned this.
> 
> > Running yarn start:dev yields a deprecation warning. This is because webpack-shell-plugin is using webpack’s old plugin API. You can follow up about this on this [issue](https://github.com/1337programming/webpack-shell-plugin/issues/61).

Thanks!
